/**
 *  $countryArea['86'] = '中国OTP通道2';
    $countryArea['11'] = '美国OTP通道1';
    $countryArea['81'] = '日本OTP通道1';
    $countryArea['82'] = '韩国OTP通道3';
    $countryArea['84'] = '越南OTP通道6';
    $countryArea['855'] = '柬埔寨OTP通道1';
    $countryArea['66'] = '泰国OTP通道3';
    $countryArea['856'] = '老挝OTP通道1';
    $countryArea['91'] = '印度OTP通道1';
    $countryArea['7'] = '俄罗斯OTP通道1';
    $countryArea['49'] = '德国OTP通道1';
    $countryArea['44'] = '英国OTP通道1';
    $countryArea['33'] = '法国OTP通道1';
    $countryArea['39'] = '意大利OTP通道1';
 */

export const areaCode = [{
		label: "中国",
		value: "86",
		"short": "CN",
		"name": "中国",
		"en": "China",
		"tel": "86",
		"flag": "/static/flag/cn.png"
	},
	{
		label: "美国",
		value: "1",
		"short": "US",
		"name": "美国",
		"en": "UnitedStatesofAmerica",
		"tel": "1",
		"flag": "/static/flag/us.png"
	},
	{
		label: "日本",
		value: "81",
		"short": "JP",
		"name": "日本",
		"en": "Japan",
		"tel": "81",
		"flag": "/static/flag/jp.png"
	},
	{
		label: "韩国",
		value: "82",
		"short": "KR",
		"name": "韩国",
		"en": "Korea",
		"tel": "82",
		"flag": "/static/flag/kr.png"
	},
	{
		label: "越南",
		value: "84",
		"short": "VN",
		"name": "越南",
		"en": "Vietnam",
		"tel": "84",
		"flag": "/static/flag/vn.png"
	},
	{
		label: "柬埔寨",
		value: "855",
		"short": "KH",
		"name": "柬埔寨",
		"en": "Kampuchea(Cambodia)",
		"tel": "855",
		"flag": "/static/flag/kh.png"
	},
	{
		label: "老挝",
		value: "856",
		"short": "LA",
		"name": "老挝",
		"en": "Laos",
		"tel": "856",
		"flag": "/static/flag/la.png"
	},
	{
		label: "泰国",
		value: "66",
		"short": "TH",
		"name": "泰国",
		"en": "Thailand",
		"tel": "66",
		"flag": "/static/flag/th.png"
	},
	{
		label: "印度",
		value: "91",
		"short": "IN",
		"name": "印度",
		"en": "India",
		"tel": "91",
		"flag": "/static/flag/in.png"
	},
	{
		label: "俄罗斯",
		value: "7",
		"short": "RU",
		"name": "俄罗斯",
		"en": "Russia",
		"tel": "7",
		"flag": "/static/flag/ru.png"
	},
	{
		label: "德国",
		value: "49",
		"short": "DE",
		"name": "德国",
		"en": "Germany",
		"tel": "49",
		"flag": "/static/flag/de.png"
	},
	{
		label: "英国",
		value: "44",
		"short": "GB",
		"name": "英国",
		"en": "UnitedKiongdom",
		"tel": "44",
		"flag": "/static/flag/gb.png"
	},
	{
		label: "法国",
		value: "33",
		"short": "FR",
		"name": "法国",
		"en": "France",
		"tel": "33",
		"flag": "/static/flag/fr.png"
	},
	{
		label: "意大利",
		value: "39",
		"short": "IT",
		"name": "意大利",
		"en": "Italy",
		"tel": "39",
		"flag": "/static/flag/it.png"
	},

	// { label: "马来西亚", value: "60" },
	// { label: "印度尼西亚", value: "62" },
	// { label: "菲律宾", value: "63" },
	// { label: "新加坡", value: "65" },
	// { label: "文莱", value: "673" },
	// { label: "朝鲜", value: "850" },
	// { label: "香港(中国)", value: "852" },
	// { label: "澳门(中国)", value: "853" }, 
	// { label: "台湾(中国)", value: "886" },
	// { label: "孟加拉国", value: "880" },
	// { label: "土耳其", value: "90" },
	// { label: "巴基斯坦", value: "92" },
	// { label: "阿富汗", value: "93" },
	// { label: "斯里兰卡", value: "94" },
	// { label: "缅甸", value: "95" },
	// { label: "马尔代夫", value: "960" },
	// { label: "黎巴嫩", value: "961" },
	// { label: "约旦", value: "962" },
	// { label: "叙利亚", value: "963" },
	// { label: "伊拉克", value: "964" },
	// { label: "科威特", value: "965" },
	// { label: "沙特阿拉伯", value: "966" },
	// { label: "阿曼", value: "968" },
	// { label: "以色列", value: "972" },
	// { label: "巴林", value: "973" },
	// { label: "卡塔尔", value: "974" },
	// { label: "不丹", value: "975" },
	// { label: "蒙古", value: "976" },
	// { label: "尼泊尔", value: "977" },
	// { label: "伊朗", value: "98" },
	// { label: "塞浦路斯", value: "357" },
	// { label: "巴勒斯坦", value: "970" },
	// { label: "阿联酋", value: "971" },
	// { label: "希腊", value: "30" },
	// { label: "荷兰", value: "31" },
	// { label: "比利时", value: "32" },
	// { label: "西班牙", value: "34" },
	// { label: "直布罗陀", value: "350" },
	// { label: "葡萄牙", value: "351" },
	// { label: "卢森堡", value: "352" },
	// { label: "爱尔兰", value: "353" },
	// { label: "冰岛", value: "354" },
	// { label: "阿尔巴尼亚", value: "355" },
	// { label: "马耳他", value: "356" },
	// { label: "安道尔", value: "376" },
	// { label: "芬兰", value: "358" },
	// { label: "保加利亚", value: "359" },
	// { label: "匈牙利", value: "36" },
	// { label: "南斯拉夫", value: "381" }, 
	// { label: "圣马力诺", value: "378" },
	// { label: "梵蒂冈", value: "3906698" },
	// { label: "罗马尼亚", value: "40" },
	// { label: "瑞士", value: "41" },
	// { label: "列支敦士登", value: "423" },
	// { label: "奥地利", value: "43" },
	// { label: "丹麦", value: "45" },
	// { label: "瑞典", value: "46" },
	// { label: "挪威", value: "47" },
	// { label: "波兰", value: "48" },
	// { label: "捷克", value: "420" },
	// { label: "斯洛伐克", value: "421" },
	// { label: "摩纳哥", value: "377" },
	// { label: "马其顿", value: "389" },
	// { label: "科罗地亚", value: "385" },
	// { label: "斯洛文尼亚", value: "386" },
	// { label: "波斯尼亚和塞哥维那", value: "387" },
	// { label: "亚美尼亚共和国", value: "374" },
	// { label: "白俄罗斯共和国", value: "375" },
	// { label: "格鲁吉亚共和国", value: "995" },
	// { label: "哈萨克斯坦共和国", value: "7" },
	// { label: "吉尔吉斯坦共和国", value: "996" },
	// { label: "乌兹别克斯坦共和国", value: "998" },
	// { label: "塔吉克斯坦共和国", value: "992" },
	// { label: "土库曼斯坦共和国", value: "993" },
	// { label: "乌克兰", value: "380" },
	// { label: "立陶宛", value: "370" },
	// { label: "拉脱维亚", value: "371" },
	// { label: "爱沙尼亚", value: "372" },
	// { label: "摩尔多瓦", value: "373" },
	// { label: "埃及", value: "20" },
	// { label: "摩洛哥", value: "212" },
	// { label: "阿尔及利亚", value: "213" },
	// { label: "突尼斯", value: "216" },
	// { label: "利比亚", value: "218" },
	// { label: "冈比亚", value: "220" },
	// { label: "塞内加尔", value: "221" },
	// { label: "毛里塔尼亚", value: "222" },
	// { label: "马里", value: "223" },
	// { label: "几内亚", value: "224" },
	// { label: "科特迪瓦", value: "225" },
	// { label: "布基拉法索", value: "226" },
	// { label: "尼日尔", value: "227" },
	// { label: "多哥", value: "228" },
	// { label: "贝宁", value: "229" },
	// { label: "毛里求斯", value: "230" },
	// { label: "利比里亚", value: "231" },
	// { label: "塞拉利昂", value: "232" },
	// { label: "加纳", value: "233" },
	// { label: "尼日利亚", value: "234" },
	// { label: "乍得", value: "235" },
	// { label: "中非", value: "236" },
	// { label: "喀麦隆", value: "237" },
	// { label: "佛得角", value: "238" },
	// { label: "圣多美", value: "239" },
	// { label: "普林西比", value: "239" },
];